import { title } from 'process'
import React from 'react'
export const metadata={
  title:"next.js",
  description:"Generated by next.js"
}
const page = () => {
  return (
    <div>
       <h1 className="text-3xl font-bold text-blue-600">
      Hello Next.js Practice!
    </h1>

    </div>
  )
}

export default page
